//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentalHealthcare.Application.Resources.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MentalHealthcare.Application.Resources.Localization.Resources.Messages_ar", typeof(Messages_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string ThumbnailInvalidSize {
            get {
                return ResourceManager.GetString("ThumbnailInvalidSize", resourceCulture);
            }
        }
        
        internal static string ThumbnailRequired {
            get {
                return ResourceManager.GetString("ThumbnailRequired", resourceCulture);
            }
        }
        
        internal static string ThumbnailInvalidType {
            get {
                return ResourceManager.GetString("ThumbnailInvalidType", resourceCulture);
            }
        }
        
        internal static string ThumbnailInvalidExtension {
            get {
                return ResourceManager.GetString("ThumbnailInvalidExtension", resourceCulture);
            }
        }
        
        internal static string IconRequired {
            get {
                return ResourceManager.GetString("IconRequired", resourceCulture);
            }
        }
        
        internal static string IconInvalidType {
            get {
                return ResourceManager.GetString("IconInvalidType", resourceCulture);
            }
        }
        
        internal static string IconInvalidSize {
            get {
                return ResourceManager.GetString("IconInvalidSize", resourceCulture);
            }
        }
        
        internal static string PageSizeGreaterThanZero {
            get {
                return ResourceManager.GetString("PageSizeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PageSizeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("PageSizeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        internal static string SearchTermNotEmpty {
            get {
                return ResourceManager.GetString("SearchTermNotEmpty", resourceCulture);
            }
        }
        
        internal static string SearchTermMaxLength {
            get {
                return ResourceManager.GetString("SearchTermMaxLength", resourceCulture);
            }
        }
        
        internal static string SearchTermNoHtml {
            get {
                return ResourceManager.GetString("SearchTermNoHtml", resourceCulture);
            }
        }
        
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        internal static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        internal static string EmailNoHtml {
            get {
                return ResourceManager.GetString("EmailNoHtml", resourceCulture);
            }
        }
        
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        internal static string NameRequiredIfProvided {
            get {
                return ResourceManager.GetString("NameRequiredIfProvided", resourceCulture);
            }
        }
        
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        internal static string NameNoHtml {
            get {
                return ResourceManager.GetString("NameNoHtml", resourceCulture);
            }
        }
        
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        internal static string PhoneRequiredIfProvided {
            get {
                return ResourceManager.GetString("PhoneRequiredIfProvided", resourceCulture);
            }
        }
        
        internal static string PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("PhoneInvalidFormat", resourceCulture);
            }
        }
        
        internal static string PhoneNoHtml {
            get {
                return ResourceManager.GetString("PhoneNoHtml", resourceCulture);
            }
        }
        
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        internal static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        internal static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        internal static string UsernameNoHtml {
            get {
                return ResourceManager.GetString("UsernameNoHtml", resourceCulture);
            }
        }
        
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        internal static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        internal static string PasswordNoHtml {
            get {
                return ResourceManager.GetString("PasswordNoHtml", resourceCulture);
            }
        }
        
        internal static string PasswordLowercase {
            get {
                return ResourceManager.GetString("PasswordLowercase", resourceCulture);
            }
        }
        
        internal static string PasswordUppercase {
            get {
                return ResourceManager.GetString("PasswordUppercase", resourceCulture);
            }
        }
        
        internal static string PasswordNoCommonSequences {
            get {
                return ResourceManager.GetString("PasswordNoCommonSequences", resourceCulture);
            }
        }
        
        internal static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        internal static string ValueDigitsOnlyNoHtml {
            get {
                return ResourceManager.GetString("ValueDigitsOnlyNoHtml", resourceCulture);
            }
        }
        
        internal static string ValueNoHtml {
            get {
                return ResourceManager.GetString("ValueNoHtml", resourceCulture);
            }
        }
        
        internal static string ValueRequiredNoHtml {
            get {
                return ResourceManager.GetString("ValueRequiredNoHtml", resourceCulture);
            }
        }
        
        internal static string BirthDateMaxAge {
            get {
                return ResourceManager.GetString("BirthDateMaxAge", resourceCulture);
            }
        }
        
        internal static string BirthDateFuture {
            get {
                return ResourceManager.GetString("BirthDateFuture", resourceCulture);
            }
        }
        
        internal static string PriceNullableNonNegative {
            get {
                return ResourceManager.GetString("PriceNullableNonNegative", resourceCulture);
            }
        }
        
        internal static string IdNullablePositive {
            get {
                return ResourceManager.GetString("IdNullablePositive", resourceCulture);
            }
        }
        
        internal static string IdPositive {
            get {
                return ResourceManager.GetString("IdPositive", resourceCulture);
            }
        }
        
        internal static string PriceNonNegative {
            get {
                return ResourceManager.GetString("PriceNonNegative", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyAdmin {
            get {
                return ResourceManager.GetString("EmailAlreadyAdmin", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyPending {
            get {
                return ResourceManager.GetString("EmailAlreadyPending", resourceCulture);
            }
        }
        
        internal static string AdminNotPending {
            get {
                return ResourceManager.GetString("AdminNotPending", resourceCulture);
            }
        }
        
        internal static string AdminRegistrationFailed {
            get {
                return ResourceManager.GetString("AdminRegistrationFailed", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        internal static string OldEmailNotFound {
            get {
                return ResourceManager.GetString("OldEmailNotFound", resourceCulture);
            }
        }
        
        internal static string AdMarkedInactive {
            get {
                return ResourceManager.GetString("AdMarkedInactive", resourceCulture);
            }
        }
        
        internal static string AdCreatedSuccess {
            get {
                return ResourceManager.GetString("AdCreatedSuccess", resourceCulture);
            }
        }
        
        internal static string ImageSizeExceedsLimit {
            get {
                return ResourceManager.GetString("ImageSizeExceedsLimit", resourceCulture);
            }
        }
        
        internal static string AdNotFound {
            get {
                return ResourceManager.GetString("AdNotFound", resourceCulture);
            }
        }
        
        internal static string AdNameLength {
            get {
                return ResourceManager.GetString("AdNameLength", resourceCulture);
            }
        }
        
        internal static string AdMustHaveImage {
            get {
                return ResourceManager.GetString("AdMustHaveImage", resourceCulture);
            }
        }
        
        internal static string AdDescriptionLength {
            get {
                return ResourceManager.GetString("AdDescriptionLength", resourceCulture);
            }
        }
        
        internal static string AdminIdentityNotExist {
            get {
                return ResourceManager.GetString("AdminIdentityNotExist", resourceCulture);
            }
        }
        
        internal static string NoCartFound {
            get {
                return ResourceManager.GetString("NoCartFound", resourceCulture);
            }
        }
        
        internal static string CourseSectionsUpdateBlocked {
            get {
                return ResourceManager.GetString("CourseSectionsUpdateBlocked", resourceCulture);
            }
        }
        
        internal static string InvalidHelpCenterItemType {
            get {
                return ResourceManager.GetString("InvalidHelpCenterItemType", resourceCulture);
            }
        }
        
        internal static string InvalidOrdersForSections {
            get {
                return ResourceManager.GetString("InvalidOrdersForSections", resourceCulture);
            }
        }
        
        internal static string LessonNotFound {
            get {
                return ResourceManager.GetString("LessonNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidOrderForLessons {
            get {
                return ResourceManager.GetString("InvalidOrderForLessons", resourceCulture);
            }
        }
        
        internal static string OrderValuesMustBeSequential {
            get {
                return ResourceManager.GetString("OrderValuesMustBeSequential", resourceCulture);
            }
        }
        
        internal static string SectionHasNoLessons {
            get {
                return ResourceManager.GetString("SectionHasNoLessons", resourceCulture);
            }
        }
        
        internal static string OrderUpdateBlockedStudentsJoined {
            get {
                return ResourceManager.GetString("OrderUpdateBlockedStudentsJoined", resourceCulture);
            }
        }
        
        internal static string PermissionDeniedUpdateLessonsOrder {
            get {
                return ResourceManager.GetString("PermissionDeniedUpdateLessonsOrder", resourceCulture);
            }
        }
        
        internal static string InvalidItemType {
            get {
                return ResourceManager.GetString("InvalidItemType", resourceCulture);
            }
        }
        
        internal static string InvalidExpireDateFormat {
            get {
                return ResourceManager.GetString("InvalidExpireDateFormat", resourceCulture);
            }
        }
        
        internal static string InvoiceNotFound {
            get {
                return ResourceManager.GetString("InvoiceNotFound", resourceCulture);
            }
        }
        
        internal static string ExpireDateMustBeFuture {
            get {
                return ResourceManager.GetString("ExpireDateMustBeFuture", resourceCulture);
            }
        }
        
        internal static string CourseIdsMustBeUnique {
            get {
                return ResourceManager.GetString("CourseIdsMustBeUnique", resourceCulture);
            }
        }
        
        internal static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        internal static string CourseNotFree {
            get {
                return ResourceManager.GetString("CourseNotFree", resourceCulture);
            }
        }
        
        internal static string CourseAlreadyOwned {
            get {
                return ResourceManager.GetString("CourseAlreadyOwned", resourceCulture);
            }
        }
        
        internal static string CartMaxCapacityReached {
            get {
                return ResourceManager.GetString("CartMaxCapacityReached", resourceCulture);
            }
        }
        
        internal static string AlreadyJoinedCourse {
            get {
                return ResourceManager.GetString("AlreadyJoinedCourse", resourceCulture);
            }
        }
        
        internal static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        internal static string InvalidOrdersForResources {
            get {
                return ResourceManager.GetString("InvalidOrdersForResources", resourceCulture);
            }
        }
        
        internal static string CourseNotInCart {
            get {
                return ResourceManager.GetString("CourseNotInCart", resourceCulture);
            }
        }
        
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        internal static string InvoiceIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvoiceIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string InvalidLessonIdOrNotInCourse {
            get {
                return ResourceManager.GetString("InvalidLessonIdOrNotInCourse", resourceCulture);
            }
        }
        
        internal static string UserNotEnrolledInCourse {
            get {
                return ResourceManager.GetString("UserNotEnrolledInCourse", resourceCulture);
            }
        }
        
        internal static string CourseCompletionRequiredForReview {
            get {
                return ResourceManager.GetString("CourseCompletionRequiredForReview", resourceCulture);
            }
        }
        
        internal static string CourseAlreadyInCart {
            get {
                return ResourceManager.GetString("CourseAlreadyInCart", resourceCulture);
            }
        }
        
        internal static string InvoiceNotPending {
            get {
                return ResourceManager.GetString("InvoiceNotPending", resourceCulture);
            }
        }
        
        internal static string PromoCodeNameRequired {
            get {
                return ResourceManager.GetString("PromoCodeNameRequired", resourceCulture);
            }
        }
        
        internal static string ReviewsLimitReached {
            get {
                return ResourceManager.GetString("ReviewsLimitReached", resourceCulture);
            }
        }
        
        internal static string InvalidOrderStatus {
            get {
                return ResourceManager.GetString("InvalidOrderStatus", resourceCulture);
            }
        }
        
        internal static string CompletePreviousLessonFirst {
            get {
                return ResourceManager.GetString("CompletePreviousLessonFirst", resourceCulture);
            }
        }
        
        internal static string UserAlreadyHasCourse {
            get {
                return ResourceManager.GetString("UserAlreadyHasCourse", resourceCulture);
            }
        }
        
        internal static string InvalidCourseIdsProvided {
            get {
                return ResourceManager.GetString("InvalidCourseIdsProvided", resourceCulture);
            }
        }
        
        internal static string UnknownContentType {
            get {
                return ResourceManager.GetString("UnknownContentType", resourceCulture);
            }
        }
        
        internal static string CourseIconMissing {
            get {
                return ResourceManager.GetString("CourseIconMissing", resourceCulture);
            }
        }
        
        internal static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
        
        internal static string PdfUploadFailed {
            get {
                return ResourceManager.GetString("PdfUploadFailed", resourceCulture);
            }
        }
        
        internal static string VideoDeletionFailed {
            get {
                return ResourceManager.GetString("VideoDeletionFailed", resourceCulture);
            }
        }
        
        internal static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        internal static string PendingUploadNotFound {
            get {
                return ResourceManager.GetString("PendingUploadNotFound", resourceCulture);
            }
        }
        
        internal static string CourseSectionDeletionError {
            get {
                return ResourceManager.GetString("CourseSectionDeletionError", resourceCulture);
            }
        }
        
        internal static string ImageUploadFailed {
            get {
                return ResourceManager.GetString("ImageUploadFailed", resourceCulture);
            }
        }
        
        internal static string VideoCreationUnexpectedError {
            get {
                return ResourceManager.GetString("VideoCreationUnexpectedError", resourceCulture);
            }
        }
        
        internal static string OldImageDeletionError {
            get {
                return ResourceManager.GetString("OldImageDeletionError", resourceCulture);
            }
        }
        
        internal static string CourseLessonsUpdateError {
            get {
                return ResourceManager.GetString("CourseLessonsUpdateError", resourceCulture);
            }
        }
        
        internal static string CoursePromoCodeAlreadyExists {
            get {
                return ResourceManager.GetString("CoursePromoCodeAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ResourceDeletionFailed {
            get {
                return ResourceManager.GetString("ResourceDeletionFailed", resourceCulture);
            }
        }
        
        internal static string UnexpectedRole {
            get {
                return ResourceManager.GetString("UnexpectedRole", resourceCulture);
            }
        }
        
        internal static string DeleteReviewNotAllowed {
            get {
                return ResourceManager.GetString("DeleteReviewNotAllowed", resourceCulture);
            }
        }
        
        internal static string ProfileDataNotFound {
            get {
                return ResourceManager.GetString("ProfileDataNotFound", resourceCulture);
            }
        }
        
        internal static string UsernameAlreadyTaken {
            get {
                return ResourceManager.GetString("UsernameAlreadyTaken", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyTaken {
            get {
                return ResourceManager.GetString("EmailAlreadyTaken", resourceCulture);
            }
        }
        
        internal static string EmailNotRegisteredAsAdmin {
            get {
                return ResourceManager.GetString("EmailNotRegisteredAsAdmin", resourceCulture);
            }
        }
        
        internal static string UserCreationFailed {
            get {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }
        
        internal static string LessonNotInCourse {
            get {
                return ResourceManager.GetString("LessonNotInCourse", resourceCulture);
            }
        }
        
        internal static string NotEnrolledInCourse {
            get {
                return ResourceManager.GetString("NotEnrolledInCourse", resourceCulture);
            }
        }
        
        internal static string WatchPreviousLessonsFirst {
            get {
                return ResourceManager.GetString("WatchPreviousLessonsFirst", resourceCulture);
            }
        }
        
        internal static string FailedToUploadIcon {
            get {
                return ResourceManager.GetString("FailedToUploadIcon", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string FailedToCreateVideoFolder {
            get {
                return ResourceManager.GetString("FailedToCreateVideoFolder", resourceCulture);
            }
        }
        
        internal static string SectionShouldBeEmptyToDelete {
            get {
                return ResourceManager.GetString("SectionShouldBeEmptyToDelete", resourceCulture);
            }
        }
        
        internal static string FailedToUploadImage {
            get {
                return ResourceManager.GetString("FailedToUploadImage", resourceCulture);
            }
        }
        
        internal static string FailedToDeleteIcon {
            get {
                return ResourceManager.GetString("FailedToDeleteIcon", resourceCulture);
            }
        }
        
        internal static string ErrorRemovingLesson {
            get {
                return ResourceManager.GetString("ErrorRemovingLesson", resourceCulture);
            }
        }
        
        internal static string ErrorAddingCourseLesson {
            get {
                return ResourceManager.GetString("ErrorAddingCourseLesson", resourceCulture);
            }
        }
        
        internal static string LessonNoResourcesToUpdate {
            get {
                return ResourceManager.GetString("LessonNoResourcesToUpdate", resourceCulture);
            }
        }
        
        internal static string ErrorUpdatingCourseSections {
            get {
                return ResourceManager.GetString("ErrorUpdatingCourseSections", resourceCulture);
            }
        }
        
        internal static string CanOnlyChangeToExpired {
            get {
                return ResourceManager.GetString("CanOnlyChangeToExpired", resourceCulture);
            }
        }
        
        internal static string LessonHasNoResources {
            get {
                return ResourceManager.GetString("LessonHasNoResources", resourceCulture);
            }
        }
        
        internal static string CanOnlyChangeToPending {
            get {
                return ResourceManager.GetString("CanOnlyChangeToPending", resourceCulture);
            }
        }
        
        internal static string CanOnlyChangeToCancelled {
            get {
                return ResourceManager.GetString("CanOnlyChangeToCancelled", resourceCulture);
            }
        }
        
        internal static string StatusChangeNotAllowed {
            get {
                return ResourceManager.GetString("StatusChangeNotAllowed", resourceCulture);
            }
        }
    }
}
