//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MentalHealthcare.Application.Resources.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MentalHealthcare.Application.Resources.Localization.Resources.Messages_en", typeof(Messages_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string ThumbnailInvalidSize {
            get {
                return ResourceManager.GetString("ThumbnailInvalidSize", resourceCulture);
            }
        }
        
        internal static string ThumbnailRequired {
            get {
                return ResourceManager.GetString("ThumbnailRequired", resourceCulture);
            }
        }
        
        internal static string ThumbnailInvalidType {
            get {
                return ResourceManager.GetString("ThumbnailInvalidType", resourceCulture);
            }
        }
        
        internal static string IconRequired {
            get {
                return ResourceManager.GetString("IconRequired", resourceCulture);
            }
        }
        
        internal static string IconInvalidType {
            get {
                return ResourceManager.GetString("IconInvalidType", resourceCulture);
            }
        }
        
        internal static string IconInvalidSize {
            get {
                return ResourceManager.GetString("IconInvalidSize", resourceCulture);
            }
        }
        
        internal static string PageSizeGreaterThanZero {
            get {
                return ResourceManager.GetString("PageSizeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PageSizeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("PageSizeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        internal static string SearchTermNotEmpty {
            get {
                return ResourceManager.GetString("SearchTermNotEmpty", resourceCulture);
            }
        }
        
        internal static string SearchTermMaxLength {
            get {
                return ResourceManager.GetString("SearchTermMaxLength", resourceCulture);
            }
        }
        
        internal static string SearchTermNoHtml {
            get {
                return ResourceManager.GetString("SearchTermNoHtml", resourceCulture);
            }
        }
        
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        internal static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        internal static string EmailNoHtml {
            get {
                return ResourceManager.GetString("EmailNoHtml", resourceCulture);
            }
        }
        
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        internal static string NameRequiredIfProvided {
            get {
                return ResourceManager.GetString("NameRequiredIfProvided", resourceCulture);
            }
        }
        
        internal static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        internal static string NameNoHtml {
            get {
                return ResourceManager.GetString("NameNoHtml", resourceCulture);
            }
        }
        
        internal static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        internal static string PhoneRequiredIfProvided {
            get {
                return ResourceManager.GetString("PhoneRequiredIfProvided", resourceCulture);
            }
        }
        
        internal static string PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("PhoneInvalidFormat", resourceCulture);
            }
        }
        
        internal static string PhoneNoHtml {
            get {
                return ResourceManager.GetString("PhoneNoHtml", resourceCulture);
            }
        }
        
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        internal static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        internal static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        internal static string UsernameNoHtml {
            get {
                return ResourceManager.GetString("UsernameNoHtml", resourceCulture);
            }
        }
        
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        internal static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        internal static string PasswordNoHtml {
            get {
                return ResourceManager.GetString("PasswordNoHtml", resourceCulture);
            }
        }
        
        internal static string PasswordNoCommonSequences {
            get {
                return ResourceManager.GetString("PasswordNoCommonSequences", resourceCulture);
            }
        }
        
        internal static string PasswordLowercase {
            get {
                return ResourceManager.GetString("PasswordLowercase", resourceCulture);
            }
        }
        
        internal static string PasswordUppercase {
            get {
                return ResourceManager.GetString("PasswordUppercase", resourceCulture);
            }
        }
        
        internal static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        internal static string ValueDigitsOnlyNoHtml {
            get {
                return ResourceManager.GetString("ValueDigitsOnlyNoHtml", resourceCulture);
            }
        }
        
        internal static string ValueNoHtml {
            get {
                return ResourceManager.GetString("ValueNoHtml", resourceCulture);
            }
        }
        
        internal static string ValueRequiredNoHtml {
            get {
                return ResourceManager.GetString("ValueRequiredNoHtml", resourceCulture);
            }
        }
        
        internal static string BirthDateFuture {
            get {
                return ResourceManager.GetString("BirthDateFuture", resourceCulture);
            }
        }
        
        internal static string BirthDateMaxAge {
            get {
                return ResourceManager.GetString("BirthDateMaxAge", resourceCulture);
            }
        }
        
        internal static string PriceNonNegative {
            get {
                return ResourceManager.GetString("PriceNonNegative", resourceCulture);
            }
        }
        
        internal static string PriceNullableNonNegative {
            get {
                return ResourceManager.GetString("PriceNullableNonNegative", resourceCulture);
            }
        }
        
        internal static string IdPositive {
            get {
                return ResourceManager.GetString("IdPositive", resourceCulture);
            }
        }
        
        internal static string IdNullablePositive {
            get {
                return ResourceManager.GetString("IdNullablePositive", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyPending {
            get {
                return ResourceManager.GetString("EmailAlreadyPending", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyAdmin {
            get {
                return ResourceManager.GetString("EmailAlreadyAdmin", resourceCulture);
            }
        }
        
        internal static string AdminNotPending {
            get {
                return ResourceManager.GetString("AdminNotPending", resourceCulture);
            }
        }
        
        internal static string AdminRegistrationFailed {
            get {
                return ResourceManager.GetString("AdminRegistrationFailed", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationSubject", resourceCulture);
            }
        }
        
        internal static string EmailConfirmationFailed {
            get {
                return ResourceManager.GetString("EmailConfirmationFailed", resourceCulture);
            }
        }
        
        internal static string AdminIdentityNotExist {
            get {
                return ResourceManager.GetString("AdminIdentityNotExist", resourceCulture);
            }
        }
        
        internal static string OldEmailNotFound {
            get {
                return ResourceManager.GetString("OldEmailNotFound", resourceCulture);
            }
        }
    }
}
